=== mani-4444/wp-assignment-1/courses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="learnhub">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="courses">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="course" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="instructor" type="xs:string"/>
                    <xs:element name="price">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:decimal">
                            <xs:attribute name="currency" type="xs:string" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="rating">
                      <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:minInclusive value="0"/>
                          <xs:maxInclusive value="5"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="duration" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mani-4444/wp-assignment-1/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<learnhub
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="courses.xsd"
>
  <courses>
    <course id="C101">
      <title>Web Development Basics</title>
      <instructor>Mr. Goutham</instructor>
      <price currency="INR">1999</price>
      <rating>4.3</rating>
      <duration>8 Weeks</duration>
    </course>

    <course id="C102">
      <title>AIML for Beginners</title>
      <instructor>Mr. Manideep</instructor>
      <price currency="INR">2499</price>
      <rating>4.4</rating>
      <duration>8 Weeks</duration>
    </course>

    <course id="C103">
      <title>Database Fundamentals</title>
      <instructor>Mr. Arun</instructor>
      <price currency="INR">1799</price>
      <rating>4.1</rating>
      <duration>8 Weeks</duration>
    </course>
  </courses>
</learnhub>
